#!/usr/bin/env python3
"""Helper script to guide you through getting Zotero credentials."""

print("=" * 70)
print("  HOW TO GET YOUR ZOTERO USER ID AND API KEY")
print("=" * 70)
print()
print("Follow these steps:")
print()
print("1. Open this URL in your browser:")
print("   👉 https://www.zotero.org/settings/keys")
print()
print("2. Sign in to your Zotero account (if not already signed in)")
print()
print("3. You'll see your User ID displayed at the top:")
print("   📝 'Your userID for use in API calls is XXXXXXXX'")
print("   Copy this number - this is your user_id")
print()
print("4. Create a new API key:")
print("   - Click 'Create new private key'")
print("   - Give it a description (e.g., 'lit-llmed integration')")
print("   - Set permissions:")
print("     ✅ Allow library access")
print("     ✅ Allow write access (to create collections and add items)")
print("   - Click 'Save Key'")
print()
print("5. Copy the API key shown (you can only see it once!)")
print()
print("6. Update config/zotero.json with these values:")
print("   {")
print('     "api_key": "paste-your-api-key-here",')
print('     "user_id": "paste-your-user-id-here",')
print('     "library_type": "user"')
print("   }")
print()
print("7. Run the test script:")
print("   .venv/bin/python test_zotero.py")
print()
print("=" * 70)
print()
